# Generated by Django 5.0 on 2025-10-07 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoVer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('ID_Cliente', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre_Cliente', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=254)),
                ('Telefono', models.CharField(max_length=15)),
                ('Direccion', models.CharField(max_length=200)),
                ('Ciudad', models.CharField(max_length=50)),
                ('Pais', models.CharField(max_length=50)),
                ('Fecha_Registro', models.DateField(auto_now_add=True)),
                ('Tipo_Cliente', models.CharField(choices=[('individual', 'Individual'), ('mayorista', 'Mayorista'), ('corporativo', 'Corporativo')], max_length=20)),
                ('Preferencias', models.TextField(blank=True, null=True)),
                ('Fecha_Nacimiento', models.DateField(blank=True, null=True)),
                ('Genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField()),
                ('categoria', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado'), ('descontinuado', 'Descontinuado')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proveedor', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
