# Generated by Django 5.0 on 2025-10-07 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoVer', '0002_clientes_productos_delete_empleado'),
    ]

    operations = [
    ]
