# Generated by Django 5.0 on 2025-10-08 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoVer', '0004_auto_20250107_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='clientes',
            name='genero',
        ),
        migrations.AlterField(
            model_name='clientes',
            name='comuna',
            field=models.CharField(default='Santiago', max_length=50, verbose_name='Comuna'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Persona de Contacto'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='giro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Giro'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre/Razón Social'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='observaciones',
            field=models.TextField(blank=True, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='region',
            field=models.CharField(default='Metropolitana', max_length=50, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='rut',
            field=models.CharField(max_length=12, unique=True, verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.CharField(max_length=15, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_cliente',
            field=models.CharField(choices=[('consumidor_final', 'Consumidor Final'), ('contribuyente', 'Contribuyente'), ('empresa', 'Empresa')], default='consumidor_final', max_length=20, verbose_name='Tipo de Cliente'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='tipo_persona',
            field=models.CharField(choices=[('natural', 'Persona Natural'), ('juridica', 'Persona Jurídica')], default='natural', max_length=20, verbose_name='Tipo de Persona'),
        ),
    ]
