# Generated by Django 5.0 on 2025-10-08 01:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('usuario_apertura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dias_apertura', to=settings.AUTH_USER_MODEL)),
                ('usuario_cierre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dias_cierre', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Control de Día',
                'verbose_name_plural': 'Controles de Día',
                'ordering': ['-fecha'],
            },
        ),
    ]
